### ISSUE TITLE
App Request: Speedtest Tracker

### ISSUE THREAD

**Issue by fwzmhmd** [saltyorg/Sandbox#354]
# Speedtest Tracker

Speedtest Tracker is a self-hosted internet performance tracking application that runs speedtest checks against Ookla's Speedtest service.

## Why should I use this?

The main use case for Speedtest Tracker is to build a history of your internet's performance so that you can be informed when you're not receiving your ISP's advertised rates.

## Links to further information

- [x] [Link to project homepage or github](https://github.com/alexjustesen/speedtest-tracker)
- [x] [Link to documentation](https://docs.speedtest-tracker.dev/)
- [x] [Link to installation instructions](https://docs.speedtest-tracker.dev/getting-started/installation)
- [x] [Link to compose file](https://docs.speedtest-tracker.dev/getting-started/installation/installation#install-with-docker-compose-recommended)

## What are you willing to do to help?

- [x] I will you help with making docs if this gets picked up.

## Anything else you would like to add.

This is not the same as this [speed test tracker](https://github.com/henrywhitaker3/Speedtest-Tracker) which looks to be abandoned by the developer. This is also not the same as this [App Request](https://github.com/saltyorg/Sandbox/issues/296) on this repo.
